name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pogasiid/go_udp_server:latest
      
      - 
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            key: ${{ secrets.SSH_KEY }}
            username: ${{ secrets.SSH_USERNAME }}
            
            script: |
                cd ~/
                docker-compose down && docker-compose up -d
